apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-send-email-ses
spec:
  replicas: 40
  selector:
    matchLabels:
      app: worker-send-email-ses
  template:
    metadata:
      labels:
        app: worker-send-email-ses
      annotations:
        ad.datadoghq.com/worker-send-email-ses.logs: '[{"source":"worker","service":"send-email-ses"}]'
    spec:
      containers:
      - image: 194396987458.dkr.ecr.us-east-1.amazonaws.com/dreamwidth/worker:latest
        name: worker-send-email-ses
        command: ["bash"]
        args: ["/opt/startup-prod.sh", "bin/worker/send-email-ses", "-v"]
        resources:
          requests:
            cpu: 50m
            memory: 300M
        volumeMounts:
        - name: config
          mountPath: /dw/etc
          readOnly: true
        env:
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      volumes:
      - name: config
        secret:
          secretName: dw-config
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-send-email-ses
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-send-email-ses
  minReplicas: 40
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
